extends:
  - airbnb
  - prettier
parser: babel-eslint
plugins:
    - prettier
    - react
    - jsx-a11y
    - import
env:
  browser: true
  node: true
  jest: true
rules:
  react/jsx-filename-extension: off
  import/extensions: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  react/forbid-prop-types: off
  jsx-a11y/anchor-is-valid: off
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  max-len:
    - error
    - 80
